version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/usr/src/rs_crypto_msg
    ports:
      - "8000:8000"
